In [1]:
import numpy as np

In [2]:
x = np.array(range(6))
print(x)
a2 = x[np.newaxis,:]
print(a2)
a2.shape

[0 1 2 3 4 5]
[[0 1 2 3 4 5]]


(1, 6)

In [3]:
# Matrizes e arrays homogêneos(com elementos do mesmo tipo)

x = np.array([1,3,3.5, 3]) #por conter um float64, todos os elementos do array se tornam float64
print(f"x = {x}")
y = np.array([1,3,3.5, 3, "a"]) #por conter um str, todos os outros elementos do array se tornam str
print(f"y = {y}") 

# uma das diferenças entre o np array e o python list é que no array os valores do array são do mesmo tipo
print(f"type x = {type(x[0])} --- type y = {type(y[0])}")
print(f"tipo do array x: {type(x)}")

x = [1.  3.  3.5 3. ]
y = ['1' '3' '3.5' '3' 'a']
type x = <class 'numpy.float64'> --- type y = <class 'numpy.str_'>
tipo do array x: <class 'numpy.ndarray'>


In [4]:
array = np.array([1,2,3,4,5,6])
mat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(array)
print(mat)
print(f"primeira linha da mat: {mat[0]}")
print(f"primeiro elemento do array: {array[0]}")

[1 2 3 4 5 6]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
primeira linha da mat: [1 2 3 4]
primeiro elemento do array: 1


### Axes são as dimensões de uma ndarray(np.array)

In [5]:
# A matriz abaixo tem o primeiro axis com tamanho 2(linhas) e o segundo axis com tamanho 3(colunas)
mat = np.array([[0,0,0], [1,1,1]])
print(mat)

[[0 0 0]
 [1 1 1]]


### Modos de criar arrays

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
a_zeros = np.zeros(5)
print(a_zeros)

[0. 0. 0. 0. 0.]


In [8]:
a_ones = np.ones(5)
print(a_ones)

[1. 1. 1. 1. 1.]


In [9]:
# um array vazio é mais rápido de ser criado
# os valores que vão ficar são definidos, a principio, de acordo com os valores que estão na memória (?) Perguntar se é isso mesmo que entendi
a_void = np.empty(3)
print(a_void)

[0.0e+000 0.0e+000 1.6e-322]


In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
a_lins = np.linspace(0,10, num=5)
print(a_lins)

[ 0.   2.5  5.   7.5 10. ]


In [12]:
#consigo especificar o tipo de values do array
x = np.array([1,1.1,3], dtype=np.int64)
print(type(x[1]))
print(x)

<class 'numpy.int64'>
[1 1 3]


### Adicionar, remover e ordenar elementos

In [27]:
arr = np.array([2,1,5,3,7,7,4,6,8])
print(np.sort(arr))
mat = np.array([[1,4,3,2], [8,7,5,6], [12,11,10,9]])
print(np.sort(mat))

[1 2 3 4 5 6 7 7 8]
4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])
conc = np.concatenate((a,b))
print(conc)

[1 2 3 4 5 6]


In [55]:
x = np.array([[1, 2, 3], [3, 4, 3]])
y = np.array([[5,6,2]])
z = np.array([1,3,5])
print(z.ndim)
m_mat = np.concatenate((x,y), axis=0)
print(m_mat)

print(f"axes: {m_mat.ndim}") # número de axes
print(f"size: {m_mat.size}") # quantidade de elementos
print(f"shape: {m_mat.shape}") # quantidade de elementos em cada dimensão

1
[[1 2 3]
 [3 4 3]
 [5 6 2]]
axes: 2
size: 9
shape: (3, 3)


In [53]:
array_example = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [63]:
a = np.arange(8)
print(a)
b = a.reshape(2,4) # reshape retorna outro array
print(b)

c = np.reshape(a, newshape=(4,2), order='C')
print(c)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
