# Numpy: Exercícios

In [2]:
import numpy as np

## 1. Crie um vetor de zeros de tamanho 20 com o 9º e o 18ª elementos iguais à 1.

In [4]:
a_zeros = np.zeros(shape=(20))
#a_zeros[8] = 1
#a_zeros[17] = 1

a_zeros[[8,17]] = 1

print(a_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


## 2. Inverta um array Numpy (o último elemento se torna o primeiro).

In [47]:
a = np.array([1,2,3,4,5])
print(a)

# dois modos de inverter um vetor
x = np.flip(a)
rev_a = a[::-1]

print(f"::-1 = {rev_a}")
print(f"flip = {x}")

[1 2 3 4 5]
::-1 = [5 4 3 2 1]
flip = [5 4 3 2 1]


## 3. Crie uma matriz com o intervalo de 0 à 11

In [105]:
np.array(range(12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 4. Ache os índices dos elementos diferentes de 0 do array [10, 5, 0, 0, 3, 2, 0, 5, 0].

In [30]:
a = np.array([10, 5, 0, 0, 3, 2, 0, 5, 0])
print(a)
ind_nonzero = np.nonzero(a)
print(ind_nonzero)

[10  5  0  0  3  2  0  5  0]
(array([0, 1, 4, 5, 7]),)


## 5. Crie uma matriz identidade 5x5.

In [33]:
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 6. Crie um array 5x5x3 com valores aleatórios de 0 à 1 e encontre os valores máximo e mínimo.

In [94]:
tensor = np.random.default_rng().integers(2, size=(5,5,3))
#print(tensor)
print(f"maximum = { tensor.max() }")
print(f"minimum = { tensor.min() }")
print(f"shape = { tensor.shape }")

maximum = 1
minimum = 0
shape = (5, 5, 3)


## 7. Crie um array de tamanho 100 e ache o valor médio.

In [93]:
array = np.array(range(100))
print(f"média = { array.mean() }")
print(f"size = { array.size }")

média = 49.5
size = 100


## 8. Crie um array 5x5 com 1 nas bordas e 0 na parte interior (Ex. [[1, 1, 1], [1, 0, 1], [1, 1, 1]]).

In [73]:
a = np.ones(shape=(5,5))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 9. Crie uma matriz 8, 8 com os valores [1, 2, 3, 4, 5, 6, 7] acima da diagonal.

In [132]:
y = np.diagflat([1, 2, 3, 4, 5, 6, 7], 1)

#a = np.diag(np.arange(64).reshape((8,8)),1)  --- return: [ 1 10 19 28 37 46 55]

x = np.diag(np.array([1, 2, 3, 4, 5, 6, 7]), 1)

print(x)
print()
print(y)

[[0 1 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 0 0 4 0 0 0]
 [0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 6 0]
 [0 0 0 0 0 0 0 7]
 [0 0 0 0 0 0 0 0]]

[[0 1 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 0 0 4 0 0 0]
 [0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 6 0]
 [0 0 0 0 0 0 0 7]
 [0 0 0 0 0 0 0 0]]


## 10. Multiplique uma matriz 6x8 por uma matriz 8x2.

In [4]:
a = np.arange(48).reshape((6,8))
b = np.arange(16).reshape((8,2))

y = np.matmul(a,b)
x = np.dot(a,b)

print(y,y.shape)
print(x,x.shape)

[[ 280  308]
 [ 728  820]
 [1176 1332]
 [1624 1844]
 [2072 2356]
 [2520 2868]] (6, 2)
[[ 280  308]
 [ 728  820]
 [1176 1332]
 [1624 1844]
 [2072 2356]
 [2520 2868]] (6, 2)


## 11. Dado um array 1D, atribua o sinal negativo aos elementos maiores que 5 e menores que 9.

In [5]:
a = np.array(range(1,15))
print(a)
a[(a>5) & (a<9)] *= -1
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  2  3  4  5 -6 -7 -8  9 10 11 12 13 14]


## 12. Crie uma matriz com as linhas começando do valores 0 e terminando no valor 5.

In [24]:
a = np.full((10,6), range(6))
print(a)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]


## 13. Crie um array começando em 0 e terminando em 1 de tamanho 15, mas com os valores 0 e 1 excluídos.

In [56]:
x = np.linspace(start = 0, stop = 1, num=16, endpoint=False)[1:] # pego apartir do segundo elemento
print(x ,'\n', x.size)

[0.0625 0.125  0.1875 0.25   0.3125 0.375  0.4375 0.5    0.5625 0.625
 0.6875 0.75   0.8125 0.875  0.9375] 
 15


## 14. Crie um array com valores aleatórios de tamanho 20 e substitua o maior elemento por 0.

In [6]:
a = np.random.rand(20)

print(a, '\n')

print(f"maximo = {np.amax(a)}")
print(f"índice do maximo = {np.argmax(a)}")

a[np.argmax(a)] = 0

print('\n',a)

[0.94184399 0.3021101  0.32718221 0.64836374 0.55690377 0.98129209
 0.34030382 0.37707205 0.38552131 0.43617448 0.36625431 0.03064272
 0.53855178 0.21514885 0.59337305 0.22644604 0.01745146 0.26926879
 0.20485116 0.57903352] 

maximo = 0.9812920854041478
índice do maximo = 5

 [0.94184399 0.3021101  0.32718221 0.64836374 0.55690377 0.
 0.34030382 0.37707205 0.38552131 0.43617448 0.36625431 0.03064272
 0.53855178 0.21514885 0.59337305 0.22644604 0.01745146 0.26926879
 0.20485116 0.57903352]


## 15. Retorne os elementos ímpares de um array.

In [7]:
x = np.arange(20)
x = x[x%2 != 0]
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


## 16. Como converter um array float (64 bits) em um array inteiro (32 bits)?

In [64]:
# Da pra converter os tipos usando
# documentação do Data Types: https://numpy.org/doc/stable/user/basics.types.html

f = np.array(range(10), dtype=float)
print(f"{f} - tipo: {f.dtype}")
i = np.intc(f)
print(f"{i} - tipo: {i.dtype}")

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] - tipo: float64
[0 1 2 3 4 5 6 7 8 9] - tipo: int32


## 17. Subtraia a média de cada linha de uma matriz.

In [42]:
x = np.array(range(9), dtype = float).reshape((3,3))
mean_x = np.mean(x,axis=1)

print(mean_x[0:])

print(f"\nantes:\n{ x }")
x -= mean_x
print(f"\ndepois:\n{ x }")
#print(mean_x[0:])

[1. 4. 7.]

antes:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

depois:
[[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]


## 18. Como saber se um array 2D tem colunas com todos os valores iguais à 0?

In [10]:
x = np.array([[0,0,1],[0,0,1], [0,1,0]])
#print(f"primeira coluna: {x[0,:]} -- tudo zero? {np.all(x[0,:] == 0)}")
#print(f"segunda coluna: {x[1,:]} -- tudo zero? {np.all(x[1,:] == 0)}")
#print(f"terceira coluna:{x[2,:]} -- tudo zero? {np.all(x[2,:] == 0)}")

print()
print(x)
# np.any() verifica se há algum True, caso tenha retorna True. Se tudo for False, retorna False
np.any(~np.any(x, axis=0))


[[0 0 1]
 [0 0 1]
 [0 1 0]]


True

## 19. Faça uma função que recebe um array *x* e um valor *y* como entrada e encontre o valor em *x* mais próximo de *y*.

In [53]:
y = -3
x = np.random.randint(1,10,10)

print(x)
#print((np.abs(x-y)).argmin())
x[(np.abs(x-y)).argmin()]

[7 1 5 1 7 5 8 8 6 5]


1

## 20. Como trocar a posição de duas linhas em um array 2D?

In [126]:
# encontrei esse modo de fzr swap aqui: https://pythoneo.com/how-to-swap-rows-in-numpy-array/

a = np.array(range(12)).reshape((4,3))

print(f"Array original: \n{a}")

print()

#aux = a[0].copy()
#a[0] = a[-1]
#a[-1] = aux

print(a[[0,-1]])
print()
print(a[[-1,0]])
print()

a[[-1, 0]] = a[[0, -1]]
print(f"Array com swap: \n{a}")

Array original: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2]
 [ 9 10 11]]

[[ 9 10 11]
 [ 0  1  2]]

Array com swap: 
[[ 9 10 11]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  1  2]]
