In [1]:
import numpy as np

In [2]:
a = np.array(range(10))

In [3]:
print(a)
print(f"a partir do 2º elemento: {a[1:]}")
print(f"todos os elementos antes do 5º: {a[:5]}")
print(f"do 2º até o 5º: {a[1:5]}")
print(f"todos os elementos depois do penúltimo(os dois ultimos): {a[-2:]}")

[0 1 2 3 4 5 6 7 8 9]
a partir do 2º elemento: [1 2 3 4 5 6 7 8 9]
todos os elementos antes do 5º: [0 1 2 3 4]
do 2º até o 5º: [1 2 3 4]
todos os elementos depois do penúltimo(os dois ultimos): [8 9]


In [4]:
print(f"números pares do array: {a[a%2 == 0]}")
print(f"números ímpares do array: {a[a%2 != 0]}")
print(f"divisíveis por 3: {a[a%3==0]}")
print(f"números maior ou igual que 5: {a[a>=5]}")
print(f"3<x<7: {a[(a>3) & (a<7)]}")

números pares do array: [0 2 4 6 8]
números ímpares do array: [1 3 5 7 9]
divisíveis por 3: [0 3 6 9]
números maior ou igual que 5: [5 6 7 8 9]
3<x<7: [4 5 6]


In [5]:
x = np.array([1,0,0,3,5,4,1,0])
print(x)
x_indices_nonzero = np.nonzero(x) # pega o índice dos valores do array x que não são 0's
print(x_indices_nonzero)

[1 0 0 3 5 4 1 0]
(array([0, 3, 4, 5, 6]),)


In [9]:
aux = a[a<5]
print(aux)
b = np.nonzero(aux) # b é uma tupla - no lugar de aux, posso colocar a<5 q tbm funciona
print(b)

[0 1 2 3 4]
(array([1, 2, 3, 4]),)


In [15]:
coordenadas = list(b)
print(coordenadas)

[array([1, 2, 3, 4])]


In [20]:
x = np.array(range(5))
y = np.array(range(5))

print(x,y)

for i in zip(x,y):
    print(i)

z = list(zip(x,y))
print(z)

[0 1 2 3 4] [0 1 2 3 4]
(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]


In [24]:
print(x[::2])
print(a[1:8:2])

[0 2 4]
[1 3 5 7]
