In [1]:
import numpy as np

In [22]:
a = np.array([1,10,2,3,4])
print(f"type: {type(a)}")
print(f"tamanho: {a.shape}")
print(f"outra forma de ter o tamanho do array: {a.size}") # acredito que esse modo seja melhor
print(f"do segundo elementos até o quarto: {a[1:4]}")
print(f"ultimo elemento: {a[-1]}")
print(f"todos os elementos antes do 4: {a[:4]}")
print(f"soma 2 a cada elemento do array {a}: {a+2}")
print(f"dividindo por 2 cada elemento {a}: {a/2}")


b = np.array([2, 3, 4, 5, 1])
print(f"soma de {a} + {b} = {a+b}")
print(f"multiplicação de {a} * {b} = {a*b}")

type: <class 'numpy.ndarray'>
tamanho: (5,)
outra forma de ter o tamanho do array: 5
do segundo elementos até o quarto: [10  2  3]
ultimo elemento: 4
todos os elementos antes do 4: [ 1 10  2  3]
soma 2 a cada elemento do array [ 1 10  2  3  4]: [ 3 12  4  5  6]
dividindo por 2 cada elemento [ 1 10  2  3  4]: [0.5 5.  1.  1.5 2. ]
soma de [ 1 10  2  3  4] + [2 3 4 5 1] = [ 3 13  6  8  5]
multiplicação de [ 1 10  2  3  4] * [2 3 4 5 1] = [ 2 30  8 15  4]


### Funções úteis

In [33]:
print(f"soma de todos os elementos de {a}: {a.sum()}")
print(f"média dos elementos de {a}: {a.mean()}")
print(f"produtório dos elementos de {b}: {b.prod()}")

print(f"maior número de {a}: {a.max()}")
print(f"maior número de {b}: {b.max()}")
print(f"menor número de {a}: {a.min()}")
print(f"menor número de {b}: {b.min()}")

print(f"índice do maior numero de {a}: {a.argmax()}")
print(f"índice do menor numero de {a}: {a.argmin()}")

soma de todos os elementos de [ 1 10  2  3  4]: 20
média dos elementos de [ 1 10  2  3  4]: 4.0
produtório dos elementos de [2 3 4 5 1]: 120
maior número de [ 1 10  2  3  4]: 10
maior número de [2 3 4 5 1]: 5
menor número de [ 1 10  2  3  4]: 1
menor número de [2 3 4 5 1]: 1
índice do maior numero de [ 1 10  2  3  4]: 1
índice do menor numero de [ 1 10  2  3  4]: 0


In [45]:
np.arange(3) # [0 1 2]
np.arange(1,5) # [1 2 3 4]
np.arange(0, 10, 2) # [0 2 4 6 8]
np.linspace(0, 10, num=5) # [0 2.5 5 7.7 10]

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Matrizes (arrays com duas dimensões)

In [58]:
x_zeros = np.zeros(shape=(5,5)) # Matriz de 0's
print(x_zeros)

print('\n')

x_ones = np.ones(shape=(5,5))
print(x_ones)

print('\n')

x_random = np.random.random(size=(3,3))
print(x_random)

print('\n')

identity = np.eye(5) #matriz identidade 5x5
print(identity)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[0.69564462 0.50039893 0.06153755]
 [0.1361704  0.9356208  0.49898702]
 [0.69687562 0.62227044 0.69529866]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [77]:
x = np.array(
[[1, 4, 3],
[1, 2, 3],
[1, 5, 4]]
)

print(x)
print(f"primeira linha: {x[0,:]}")
print(f"ultima coluna: {x[:,-1]}")

print(f"média das linhas: {x.mean(axis=0)}")
print(f"média das colunas: {x.mean(axis=1)}")

print(f"soma das colunas: {x.sum(axis=1)}")
print(f"soma das linhas: {x.sum(axis=0)}")

print(f"soma todos os elementos: {x.sum()}")
print(f"média todos os elementos: {x.mean()}")

[[1 4 3]
 [1 2 3]
 [1 5 4]]
primeira linha: [1 4 3]
ultima coluna: [3 3 4]
média das linhas: [1.         3.66666667 3.33333333]
média das colunas: [2.66666667 2.         3.33333333]
soma das colunas: [ 8  6 10]
soma das linhas: [ 3 11 10]
soma todos os elementos: 24
média todos os elementos: 2.6666666666666665
